FROM php:8.3.6-fpm-alpine

WORKDIR /var/www/html

# Install NGINX
RUN apk update \
    && apk upgrade \
    && apk add nginx supervisor

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/www
RUN mkdir -p /run/nginx \
    && mkdir -p /tmp/logDir/

# Install wget
RUN apk add wget

# Install supervisord
COPY ./docker/supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Config php-fpm
COPY ./docker/php-fpm/www.conf /usr/local/etc/php-fpm.d/www.conf

# Install dependencies
RUN apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
  libxml2-dev curl-dev linux-headers oniguruma-dev imap-dev openssl-dev git openssh-client

# Install extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql dom curl mbstring imap opcache sockets bcmath

# Install redis php and enable
RUN pecl install redis \
  && docker-php-ext-enable redis

# Composer
RUN \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && HASH="$(wget -q -O - https://composer.github.io/installer.sig)" \
    && php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer


# Timezone BRT
RUN apk add -U tzdata
ENV TZ=America/Sao_Paulo
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

# Copy files
COPY www/ /var/www/html

# Setting permissions
RUN \
    chown -R www-data:www-data /var/lib/nginx && \
    chown -R www-data:www-data /var/www/html && \
    chown -R www-data:www-data /tmp/logDir && \
    find /var/www/html -type f -exec chmod 644 {} \; && \
    find /var/www/html -type d -exec chmod 755 {} \;

# Creating ENV
RUN touch /var/www/html/.env
RUN chown root:root /var/www/html/.env && chmod +x /var/www/html/.env

RUN echo "*  *  *  *  * /usr/local/bin/php  /var/www/html/artisan schedule:run > /dev/stdout 2>&1" > /etc/crontabs/root

EXPOSE 80 443

# Remove Build Dependencies
RUN apk del -f $PHPIZE_DEPS libxml2-dev curl-dev linux-headers oniguruma-dev imap-dev openssl-dev

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]